FROM alpine:3.8

# Create a group and user
RUN addgroup -S bitcoin \
    && adduser -S bitcoin -G bitcoin

RUN apk update \
    && apk add bitcoin bitcoin-cli

# Tell docker that all future commands should run as the bitcoin user
USER bitcoin


ENTRYPOINT ["bitcoind"]

# for regtest, launch with
# docker run -it -p 18443:18443 -v "$PWD/.bitcoin":/home/bitcoin/.bitcoin destrys/bitcoind
